// src/modules/calendario/mock-data.ts
//
// Mock data para el módulo "Calendario de Turnos" (HU-CAL-02).
// Respeta estrictamente los contratos y reproduce con fidelidad los datos
// de los wireframes para Día (28/09/2026), Semana (28 sep - 3 oct 2026) y Mes (Septiembre 2026).

import type {
  TurnoCalendario,
  ProfesorCalendario,
  MateriaCalendario,
} from "./types";

export const MOCK_PROFESORES: ProfesorCalendario[] = [
  { id: 1, nombre: "Andrés", apellido: "Pérez", materiasIds: [1, 5] },
  { id: 2, nombre: "Carlos", apellido: "Luna", materiasIds: [1] },
  { id: 3, nombre: "Pablo", apellido: "Díaz", materiasIds: [2] },
  { id: 4, nombre: "Sofía", apellido: "Acosta", materiasIds: [4] },
  { id: 5, nombre: "Lucía", apellido: "Fernández", materiasIds: [3] },
];

export const MOCK_MATERIAS: MateriaCalendario[] = [
  { id: 1, nombre: "Matemática", color: "#2563eb", duracionMinutos: 60 },
  { id: 2, nombre: "Física", color: "#7c3aed", duracionMinutos: 60 },
  { id: 3, nombre: "Química", color: "#059669", duracionMinutos: 90 },
  { id: 4, nombre: "Inglés", color: "#d97706", duracionMinutos: 45 },
  { id: 5, nombre: "Lengua", color: "#475569", duracionMinutos: 60 },
];

const TURNOS_SEMANA_BASE: TurnoCalendario[] = [
  // ─────────────────────────────────────────────────────────────
  // Lunes 28 de Septiembre 2026 (Reflejado en DayView y WeekView)
  // ─────────────────────────────────────────────────────────────
  {
    id: 101,
    codigo: "T-004501",
    fecha: "2026-09-28",
    horaInicio: "09:00",
    horaFin: "10:00",
    alumno: { id: 21, nombre: "Ana", apellido: "Molina", dni: "44123890", legajo: "A-0101" },
    profesor: { id: 3, nombre: "Pablo", apellido: "Díaz" },
    materia: { id: 2, nombre: "Física" },
    estado: "Reservado",
    puedeModificar: true,
    puedeCancelar: true,
    cantidadModificaciones: 0,
    cancelacionTardia: false,
    pagado: true,
    observaciones: "Preparación examen parcial de cinemática.",
  },
  {
    id: 102,
    codigo: "T-004502",
    fecha: "2026-09-28",
    horaInicio: "09:00",
    horaFin: "10:00",
    alumno: { id: 22, nombre: "Mateo", apellido: "Herrera", dni: "45234901", legajo: "A-0102" },
    profesor: { id: 4, nombre: "Sofía", apellido: "Acosta" },
    materia: { id: 4, nombre: "Inglés" },
    estado: "Cancelado",
    puedeModificar: false,
    puedeCancelar: false,
    cantidadModificaciones: 0,
    cancelacionTardia: true,
    pagado: false,
    observaciones: "Cancelado por el alumno con aviso previo.",
  },
  {
    id: 103,
    codigo: "T-004503",
    fecha: "2026-09-28",
    horaInicio: "10:00",
    horaFin: "11:00",
    alumno: { id: 23, nombre: "Pilar", apellido: "Ruiz", dni: "43890123", legajo: "A-0103" },
    profesor: { id: 1, nombre: "Andrés", apellido: "Pérez" },
    materia: { id: 1, nombre: "Matemática" },
    estado: "Reservado",
    puedeModificar: true,
    puedeCancelar: true,
    cantidadModificaciones: 0,
    cancelacionTardia: false,
    pagado: true,
    observaciones: null,
  },
  {
    id: 104,
    codigo: "T-004504",
    fecha: "2026-09-28",
    horaInicio: "10:00",
    horaFin: "11:00",
    alumno: { id: 21, nombre: "Ana", apellido: "Molina", dni: "44123890", legajo: "A-0101" },
    profesor: { id: 3, nombre: "Pablo", apellido: "Díaz" },
    materia: { id: 2, nombre: "Física" },
    estado: "Reservado",
    puedeModificar: true,
    puedeCancelar: true,
    cantidadModificaciones: 0,
    cancelacionTardia: false,
    pagado: true,
    observaciones: "Segunda hora continuada.",
    esSegundaHora: true,
  },
  {
    id: 105,
    codigo: "T-004505",
    fecha: "2026-09-28",
    horaInicio: "11:00",
    horaFin: "12:00",
    alumno: { id: 24, nombre: "Bruno", apellido: "Villalba", dni: "46789012", legajo: "A-0104" },
    profesor: { id: 1, nombre: "Andrés", apellido: "Pérez" },
    materia: { id: 5, nombre: "Lengua" },
    estado: "Reservado",
    puedeModificar: true,
    puedeCancelar: true,
    cantidadModificaciones: 1,
    cancelacionTardia: false,
    pagado: false,
    observaciones: null,
  },
  {
    id: 106,
    codigo: "T-004506",
    fecha: "2026-09-28",
    horaInicio: "11:00",
    horaFin: "12:00",
    alumno: { id: 25, nombre: "Julieta", apellido: "Paz", dni: "47123456", legajo: "A-0105" },
    profesor: { id: 2, nombre: "Carlos", apellido: "Luna" },
    materia: { id: 1, nombre: "Matemática" },
    estado: "Reservado",
    puedeModificar: true,
    puedeCancelar: true,
    cantidadModificaciones: 0,
    cancelacionTardia: false,
    pagado: true,
    observaciones: null,
  },
  {
    id: 107,
    codigo: "T-004507",
    fecha: "2026-09-28",
    horaInicio: "11:00",
    horaFin: "12:00",
    alumno: { id: 26, nombre: "Tomás", apellido: "Gil", dni: "45890123", legajo: "A-0106" },
    profesor: { id: 4, nombre: "Sofía", apellido: "Acosta" },
    materia: { id: 4, nombre: "Inglés" },
    estado: "Reservado",
    puedeModificar: true,
    puedeCancelar: true,
    cantidadModificaciones: 0,
    cancelacionTardia: false,
    pagado: true,
    observaciones: null,
  },
  {
    id: 108,
    codigo: "T-004508",
    fecha: "2026-09-28",
    horaInicio: "11:00",
    horaFin: "12:00",
    alumno: { id: 27, nombre: "Irene", apellido: "López", dni: "44567123", legajo: "A-0120" },
    profesor: { id: 5, nombre: "Lucía", apellido: "Fernández" },
    materia: { id: 3, nombre: "Química" },
    estado: "Reservado",
    puedeModificar: true,
    puedeCancelar: true,
    cantidadModificaciones: 0,
    cancelacionTardia: false,
    pagado: true,
    observaciones: "Química Orgánica - Nomenclatura",
  },
  {
    id: 109,
    codigo: "T-004509",
    fecha: "2026-09-28",
    horaInicio: "12:00",
    horaFin: "13:00",
    alumno: { id: 25, nombre: "Julieta", apellido: "Paz", dni: "47123456", legajo: "A-0105" },
    profesor: { id: 2, nombre: "Carlos", apellido: "Luna" },
    materia: { id: 1, nombre: "Matemática" },
    estado: "Reservado",
    puedeModificar: true,
    puedeCancelar: true,
    cantidadModificaciones: 0,
    cancelacionTardia: false,
    pagado: true,
    observaciones: "Segunda hora",
    esSegundaHora: true,
  },
  {
    id: 110,
    codigo: "T-004510",
    fecha: "2026-09-28",
    horaInicio: "12:00",
    horaFin: "13:00",
    alumno: { id: 28, nombre: "Valentina", apellido: "Sosa", dni: "48234567", legajo: "A-0107" },
    profesor: { id: 5, nombre: "Lucía", apellido: "Fernández" },
    materia: { id: 3, nombre: "Química" },
    estado: "Reservado",
    puedeModificar: true,
    puedeCancelar: true,
    cantidadModificaciones: 0,
    cancelacionTardia: false,
    pagado: true,
    observaciones: null,
  },
  {
    id: 111,
    codigo: "T-004511",
    fecha: "2026-09-28",
    horaInicio: "14:00",
    horaFin: "15:00",
    alumno: { id: 29, nombre: "Lara", apellido: "Castillo", dni: "46123987", legajo: "A-0108" },
    profesor: { id: 1, nombre: "Andrés", apellido: "Pérez" },
    materia: { id: 1, nombre: "Matemática" },
    estado: "Reservado",
    puedeModificar: true,
    puedeCancelar: true,
    cantidadModificaciones: 0,
    cancelacionTardia: false,
    pagado: true,
    observaciones: null,
  },
  {
    id: 112,
    codigo: "T-004512",
    fecha: "2026-09-28",
    horaInicio: "14:00",
    horaFin: "15:00",
    alumno: { id: 30, nombre: "Camila", apellido: "Rojas", dni: "45345678", legajo: "A-0109" },
    profesor: { id: 3, nombre: "Pablo", apellido: "Díaz" },
    materia: { id: 2, nombre: "Física" },
    estado: "Reservado",
    puedeModificar: true,
    puedeCancelar: true,
    cantidadModificaciones: 0,
    cancelacionTardia: false,
    pagado: true,
    observaciones: null,
  },
  {
    id: 113,
    codigo: "T-004513",
    fecha: "2026-09-28",
    horaInicio: "14:00",
    horaFin: "15:00",
    alumno: { id: 31, nombre: "Joaquín", apellido: "Nieto", dni: "44789123", legajo: "A-0110" },
    profesor: { id: 4, nombre: "Sofía", apellido: "Acosta" },
    materia: { id: 4, nombre: "Inglés" },
    estado: "Reservado",
    puedeModificar: true,
    puedeCancelar: true,
    cantidadModificaciones: 0,
    cancelacionTardia: false,
    pagado: true,
    observaciones: null,
  },
  // Turnos adicionales a las 14:00 para simular el caso de overflow (+4 turnos más)
  {
    id: 114,
    codigo: "T-004514",
    fecha: "2026-09-28",
    horaInicio: "14:00",
    horaFin: "15:00",
    alumno: { id: 32, nombre: "Diego", apellido: "Navarro", dni: "45678901", legajo: "A-0111" },
    profesor: { id: 1, nombre: "Andrés", apellido: "Pérez" },
    materia: { id: 1, nombre: "Matemática" },
    estado: "Reservado",
    puedeModificar: true,
    puedeCancelar: true,
    cantidadModificaciones: 0,
    cancelacionTardia: false,
    pagado: false,
    observaciones: null,
  },
  {
    id: 115,
    codigo: "T-004515",
    fecha: "2026-09-28",
    horaInicio: "14:00",
    horaFin: "15:00",
    alumno: { id: 33, nombre: "Martina", apellido: "Vega", dni: "46789123", legajo: "A-0112" },
    profesor: { id: 3, nombre: "Pablo", apellido: "Díaz" },
    materia: { id: 2, nombre: "Física" },
    estado: "Reservado",
    puedeModificar: true,
    puedeCancelar: true,
    cantidadModificaciones: 0,
    cancelacionTardia: false,
    pagado: true,
    observaciones: null,
  },
  {
    id: 116,
    codigo: "T-004516",
    fecha: "2026-09-28",
    horaInicio: "14:00",
    horaFin: "15:00",
    alumno: { id: 34, nombre: "Esteban", apellido: "Quispe", dni: "47890234", legajo: "A-0113" },
    profesor: { id: 5, nombre: "Lucía", apellido: "Fernández" },
    materia: { id: 3, nombre: "Química" },
    estado: "Reservado",
    puedeModificar: true,
    puedeCancelar: true,
    cantidadModificaciones: 0,
    cancelacionTardia: false,
    pagado: true,
    observaciones: null,
  },
  {
    id: 117,
    codigo: "T-004517",
    fecha: "2026-09-28",
    horaInicio: "14:00",
    horaFin: "15:00",
    alumno: { id: 35, nombre: "Luciana", apellido: "Méndez", dni: "48901345", legajo: "A-0114" },
    profesor: { id: 4, nombre: "Sofía", apellido: "Acosta" },
    materia: { id: 4, nombre: "Inglés" },
    estado: "Reservado",
    puedeModificar: true,
    puedeCancelar: true,
    cantidadModificaciones: 0,
    cancelacionTardia: false,
    pagado: false,
    observaciones: null,
  },
  // Turno T-004512 del wireframe en el detalle lateral (15:00 a 16:00)
  {
    id: 118,
    codigo: "T-004512",
    fecha: "2026-09-28",
    horaInicio: "15:00",
    horaFin: "16:00",
    alumno: { id: 36, nombre: "Juan", apellido: "Ortiz", dni: "45123987", legajo: "A-0142" },
    profesor: { id: 1, nombre: "Andrés", apellido: "Pérez" },
    materia: { id: 1, nombre: "Matemática" },
    estado: "Reservado",
    puedeModificar: true,
    puedeCancelar: true,
    cantidadModificaciones: 1,
    cancelacionTardia: false,
    pagado: true,
    observaciones: null,
  },
  {
    id: 119,
    codigo: "T-004519",
    fecha: "2026-09-28",
    horaInicio: "15:00",
    horaFin: "16:00",
    alumno: { id: 37, nombre: "Emma", apellido: "Benítez", dni: "47880123", legajo: "A-0151" },
    profesor: { id: 2, nombre: "Carlos", apellido: "Luna" },
    materia: { id: 1, nombre: "Matemática" },
    estado: "Reservado",
    puedeModificar: true,
    puedeCancelar: true,
    cantidadModificaciones: 0,
    cancelacionTardia: false,
    pagado: true,
    observaciones: null,
  },
  {
    id: 120,
    codigo: "T-004520",
    fecha: "2026-09-28",
    horaInicio: "15:00",
    horaFin: "16:00",
    alumno: { id: 38, nombre: "Leo", apellido: "Núñez", dni: "46234567", legajo: "A-0115" },
    profesor: { id: 3, nombre: "Pablo", apellido: "Díaz" },
    materia: { id: 2, nombre: "Física" },
    estado: "Reservado",
    puedeModificar: true,
    puedeCancelar: true,
    cantidadModificaciones: 0,
    cancelacionTardia: false,
    pagado: true,
    observaciones: null,
  },
  {
    id: 121,
    codigo: "T-004521",
    fecha: "2026-09-28",
    horaInicio: "15:00",
    horaFin: "16:00",
    alumno: { id: 39, nombre: "Sol", apellido: "Ramos", dni: "45789012", legajo: "A-0116" },
    profesor: { id: 5, nombre: "Lucía", apellido: "Fernández" },
    materia: { id: 3, nombre: "Química" },
    estado: "Reservado",
    puedeModificar: true,
    puedeCancelar: true,
    cantidadModificaciones: 0,
    cancelacionTardia: false,
    pagado: true,
    observaciones: null,
  },

  // ─────────────────────────────────────────────────────────────
  // Martes 29 de Septiembre 2026
  // ─────────────────────────────────────────────────────────────
  {
    id: 201,
    codigo: "T-004522",
    fecha: "2026-09-29",
    horaInicio: "09:00",
    horaFin: "10:00",
    alumno: { id: 25, nombre: "Julieta", apellido: "Paz", dni: "47123456", legajo: "A-0105" },
    profesor: { id: 2, nombre: "Carlos", apellido: "Luna" },
    materia: { id: 1, nombre: "Matemática" },
    estado: "Reservado",
    puedeModificar: true,
    puedeCancelar: true,
    cantidadModificaciones: 0,
    cancelacionTardia: false,
    pagado: true,
    observaciones: null,
  },
  {
    id: 202,
    codigo: "T-004523",
    fecha: "2026-09-29",
    horaInicio: "10:00",
    horaFin: "11:00",
    alumno: { id: 30, nombre: "Camila", apellido: "Rojas", dni: "45345678", legajo: "A-0109" },
    profesor: { id: 3, nombre: "Pablo", apellido: "Díaz" },
    materia: { id: 2, nombre: "Física" },
    estado: "Reservado",
    puedeModificar: true,
    puedeCancelar: true,
    cantidadModificaciones: 0,
    cancelacionTardia: false,
    pagado: true,
    observaciones: null,
  },
  {
    id: 203,
    codigo: "T-004524",
    fecha: "2026-09-29",
    horaInicio: "12:00",
    horaFin: "13:00",
    alumno: { id: 27, nombre: "Irene", apellido: "López", dni: "44567123", legajo: "A-0120" },
    profesor: { id: 5, nombre: "Lucía", apellido: "Fernández" },
    materia: { id: 3, nombre: "Química" },
    estado: "Reservado",
    puedeModificar: true,
    puedeCancelar: true,
    cantidadModificaciones: 0,
    cancelacionTardia: false,
    pagado: true,
    observaciones: null,
  },

  // ─────────────────────────────────────────────────────────────
  // Miércoles 30 de Septiembre 2026
  // ─────────────────────────────────────────────────────────────
  {
    id: 301,
    codigo: "T-004525",
    fecha: "2026-09-30",
    horaInicio: "10:00",
    horaFin: "11:00",
    alumno: { id: 28, nombre: "Valentina", apellido: "Sosa", dni: "48234567", legajo: "A-0107" },
    profesor: { id: 5, nombre: "Lucía", apellido: "Fernández" },
    materia: { id: 3, nombre: "Química" },
    estado: "Reservado",
    puedeModificar: true,
    puedeCancelar: true,
    cantidadModificaciones: 0,
    cancelacionTardia: false,
    pagado: true,
    observaciones: null,
  },
  {
    id: 302,
    codigo: "T-004526",
    fecha: "2026-09-30",
    horaInicio: "11:00",
    horaFin: "12:00",
    alumno: { id: 22, nombre: "Mateo", apellido: "Herrera", dni: "45234901", legajo: "A-0102" },
    profesor: { id: 4, nombre: "Sofía", apellido: "Acosta" },
    materia: { id: 4, nombre: "Inglés" },
    estado: "Reservado",
    puedeModificar: true,
    puedeCancelar: true,
    cantidadModificaciones: 0,
    cancelacionTardia: false,
    pagado: true,
    observaciones: null,
  },
  {
    id: 303,
    codigo: "T-004527",
    fecha: "2026-09-30",
    horaInicio: "14:00",
    horaFin: "15:00",
    alumno: { id: 36, nombre: "Juan", apellido: "Ortiz", dni: "45123987", legajo: "A-0142" },
    profesor: { id: 2, nombre: "Carlos", apellido: "Luna" },
    materia: { id: 1, nombre: "Matemática" },
    estado: "Reservado",
    puedeModificar: true,
    puedeCancelar: true,
    cantidadModificaciones: 0,
    cancelacionTardia: false,
    pagado: true,
    observaciones: null,
  },

  // ─────────────────────────────────────────────────────────────
  // Jueves 1 de Octubre 2026
  // ─────────────────────────────────────────────────────────────
  {
    id: 401,
    codigo: "T-004528",
    fecha: "2026-10-01",
    horaInicio: "09:00",
    horaFin: "10:00",
    alumno: { id: 21, nombre: "Ana", apellido: "Molina", dni: "44123890", legajo: "A-0101" },
    profesor: { id: 3, nombre: "Pablo", apellido: "Díaz" },
    materia: { id: 2, nombre: "Física" },
    estado: "Reservado",
    puedeModificar: true,
    puedeCancelar: true,
    cantidadModificaciones: 0,
    cancelacionTardia: false,
    pagado: true,
    observaciones: null,
  },
  {
    id: 402,
    codigo: "T-004529",
    fecha: "2026-10-01",
    horaInicio: "11:00",
    horaFin: "12:00",
    alumno: { id: 24, nombre: "Bruno", apellido: "Villalba", dni: "46789012", legajo: "A-0104" },
    profesor: { id: 1, nombre: "Andrés", apellido: "Pérez" },
    materia: { id: 5, nombre: "Lengua" },
    estado: "Reservado",
    puedeModificar: true,
    puedeCancelar: true,
    cantidadModificaciones: 0,
    cancelacionTardia: false,
    pagado: true,
    observaciones: null,
  },
  {
    id: 403,
    codigo: "T-004530",
    fecha: "2026-10-01",
    horaInicio: "15:00",
    horaFin: "16:00",
    alumno: { id: 38, nombre: "Leo", apellido: "Núñez", dni: "46234567", legajo: "A-0115" },
    profesor: { id: 3, nombre: "Pablo", apellido: "Díaz" },
    materia: { id: 2, nombre: "Física" },
    estado: "Reservado",
    puedeModificar: true,
    puedeCancelar: true,
    cantidadModificaciones: 0,
    cancelacionTardia: false,
    pagado: true,
    observaciones: null,
  },

  // ─────────────────────────────────────────────────────────────
  // Viernes 2 de Octubre 2026
  // ─────────────────────────────────────────────────────────────
  {
    id: 501,
    codigo: "T-004531",
    fecha: "2026-10-02",
    horaInicio: "10:00",
    horaFin: "11:00",
    alumno: { id: 25, nombre: "Julieta", apellido: "Paz", dni: "47123456", legajo: "A-0105" },
    profesor: { id: 2, nombre: "Carlos", apellido: "Luna" },
    materia: { id: 1, nombre: "Matemática" },
    estado: "Reservado",
    puedeModificar: true,
    puedeCancelar: true,
    cantidadModificaciones: 0,
    cancelacionTardia: false,
    pagado: true,
    observaciones: null,
  },
  {
    id: 502,
    codigo: "T-004532",
    fecha: "2026-10-02",
    horaInicio: "12:00",
    horaFin: "13:00",
    alumno: { id: 30, nombre: "Camila", apellido: "Rojas", dni: "45345678", legajo: "A-0109" },
    profesor: { id: 3, nombre: "Pablo", apellido: "Díaz" },
    materia: { id: 2, nombre: "Física" },
    estado: "Reservado",
    puedeModificar: true,
    puedeCancelar: true,
    cantidadModificaciones: 0,
    cancelacionTardia: false,
    pagado: true,
    observaciones: null,
  },
  {
    id: 503,
    codigo: "T-004533",
    fecha: "2026-10-02",
    horaInicio: "14:00",
    horaFin: "15:00",
    alumno: { id: 26, nombre: "Tomás", apellido: "Gil", dni: "45890123", legajo: "A-0106" },
    profesor: { id: 4, nombre: "Sofía", apellido: "Acosta" },
    materia: { id: 4, nombre: "Inglés" },
    estado: "Reservado",
    puedeModificar: true,
    puedeCancelar: true,
    cantidadModificaciones: 0,
    cancelacionTardia: false,
    pagado: true,
    observaciones: null,
  },

  // ─────────────────────────────────────────────────────────────
  // Sábado 3 de Octubre 2026
  // ─────────────────────────────────────────────────────────────
  {
    id: 601,
    codigo: "T-004534",
    fecha: "2026-10-03",
    horaInicio: "09:00",
    horaFin: "10:00",
    alumno: { id: 23, nombre: "Pilar", apellido: "Ruiz", dni: "43890123", legajo: "A-0103" },
    profesor: { id: 1, nombre: "Andrés", apellido: "Pérez" },
    materia: { id: 1, nombre: "Matemática" },
    estado: "Reservado",
    puedeModificar: true,
    puedeCancelar: true,
    cantidadModificaciones: 0,
    cancelacionTardia: false,
    pagado: true,
    observaciones: null,
  },
  {
    id: 602,
    codigo: "T-004535",
    fecha: "2026-10-03",
    horaInicio: "10:00",
    horaFin: "11:00",
    alumno: { id: 22, nombre: "Mateo", apellido: "Herrera", dni: "45234901", legajo: "A-0102" },
    profesor: { id: 4, nombre: "Sofía", apellido: "Acosta" },
    materia: { id: 4, nombre: "Inglés" },
    estado: "Reservado",
    puedeModificar: true,
    puedeCancelar: true,
    cantidadModificaciones: 0,
    cancelacionTardia: false,
    pagado: true,
    observaciones: null,
  },
];

/**
 * Resumen mensual mockeado para Septiembre 2026
 * Reproduce fielmente las cantidades del wireframe MonthView (image_2b8a5c.jpg).
 */
export const MOCK_RESUMEN_MES_SEPTIEMBRE_2026: Record<number, number> = {
  1: 14, 2: 11, 3: 16, 4: 9, 5: 4, 6: 0,
  7: 15, 8: 13, 9: 17, 10: 12, 11: 10, 12: 5, 13: 0,
  14: 16, 15: 14, 16: 18, 17: 13, 18: 11, 19: 6, 20: 0,
  21: 17, 22: 15, 23: 19, 24: 14, 25: 12, 26: 5, 27: 0,
  28: 18, 29: 12, 30: 9,
};

const ALUMNOS_POOL = [
  { id: 21, nombre: "Ana", apellido: "Molina", dni: "44123890", legajo: "A-0101" },
  { id: 22, nombre: "Mateo", apellido: "Herrera", dni: "45234901", legajo: "A-0102" },
  { id: 23, nombre: "Pilar", apellido: "Ruiz", dni: "43890123", legajo: "A-0103" },
  { id: 24, nombre: "Bruno", apellido: "Villalba", dni: "46789012", legajo: "A-0104" },
  { id: 25, nombre: "Julieta", apellido: "Paz", dni: "47123456", legajo: "A-0105" },
  { id: 26, nombre: "Tomás", apellido: "Gil", dni: "45890123", legajo: "A-0106" },
  { id: 27, nombre: "Irene", apellido: "López", dni: "44567123", legajo: "A-0120" },
  { id: 28, nombre: "Lucas", apellido: "Benítez", dni: "44567812", legajo: "A-0107" },
  { id: 29, nombre: "Valentina", apellido: "Castro", dni: "43987654", legajo: "A-0108" },
  { id: 30, nombre: "Camila", apellido: "Vega", dni: "44789012", legajo: "A-0109" },
  { id: 31, nombre: "Ignacio", apellido: "Morales", dni: "45123456", legajo: "A-0110" },
];

const FRANJAS_HORARIAS_POOL = ["09:00", "10:00", "11:00", "12:00", "14:00", "15:00"];

function generarTurnosCompletos(): TurnoCalendario[] {
  const turnos: TurnoCalendario[] = [...TURNOS_SEMANA_BASE];
  let autoId = 2000;

  const diasObjetivo: { fecha: string; target: number; agregarCancelado: boolean }[] = [
    { fecha: "2026-08-31", target: 8, agregarCancelado: false },
  ];

  for (let dia = 1; dia <= 30; dia++) {
    const target = MOCK_RESUMEN_MES_SEPTIEMBRE_2026[dia] ?? 0;
    const iso = `2026-09-${String(dia).padStart(2, "0")}`;
    const existentes = turnos.filter((t) => t.fecha === iso && t.estado === "Reservado").length;
    const faltan = Math.max(0, target - existentes);
    const agregarCancelado =
      target > 0 &&
      dia % 3 === 1 &&
      !turnos.some((t) => t.fecha === iso && t.estado === "Cancelado");

    diasObjetivo.push({ fecha: iso, target: faltan, agregarCancelado });
  }

  // Días de Octubre para completar la grilla del mes
  diasObjetivo.push(
    { fecha: "2026-10-04", target: 0, agregarCancelado: false },
    { fecha: "2026-10-05", target: 12, agregarCancelado: true },
    { fecha: "2026-10-06", target: 10, agregarCancelado: false },
    { fecha: "2026-10-07", target: 14, agregarCancelado: false },
    { fecha: "2026-10-08", target: 11, agregarCancelado: false },
    { fecha: "2026-10-09", target: 9, agregarCancelado: false },
    { fecha: "2026-10-10", target: 5, agregarCancelado: false },
    { fecha: "2026-10-11", target: 0, agregarCancelado: false }
  );

  diasObjetivo.forEach(({ fecha, target, agregarCancelado }) => {
    for (let i = 0; i < target; i++) {
      autoId++;
      const profIndex = (autoId + i) % MOCK_PROFESORES.length;
      const prof = MOCK_PROFESORES[profIndex];
      const materiaId = prof.materiasIds?.[i % (prof.materiasIds?.length || 1)] ?? 1;
      const mat = MOCK_MATERIAS.find((m) => m.id === materiaId) ?? MOCK_MATERIAS[0];
      const alumno = ALUMNOS_POOL[(autoId + i) % ALUMNOS_POOL.length];
      const horaInicio = FRANJAS_HORARIAS_POOL[i % FRANJAS_HORARIAS_POOL.length];
      const [h, m] = horaInicio.split(":").map(Number);
      const finMin = h * 60 + m + (mat.duracionMinutos ?? 60);
      const horaFin = `${String(Math.floor(finMin / 60)).padStart(2, "0")}:${String(
        finMin % 60
      ).padStart(2, "0")}`;

      turnos.push({
        id: autoId,
        codigo: `T-00${autoId}`,
        fecha,
        horaInicio,
        horaFin,
        alumno,
        profesor: { id: prof.id, nombre: prof.nombre, apellido: prof.apellido },
        materia: { id: mat.id, nombre: mat.nombre, duracionClaseMinutos: mat.duracionMinutos },
        estado: "Reservado",
        puedeModificar: true,
        puedeCancelar: true,
        cantidadModificaciones: i % 4 === 0 ? 1 : 0,
        cancelacionTardia: false,
        pagado: true,
      });
    }

    if (agregarCancelado) {
      autoId++;
      const prof = MOCK_PROFESORES[autoId % MOCK_PROFESORES.length];
      const mat =
        MOCK_MATERIAS.find((m) => m.id === (prof.materiasIds?.[0] ?? 1)) ?? MOCK_MATERIAS[0];
      const alumno = ALUMNOS_POOL[autoId % ALUMNOS_POOL.length];
      turnos.push({
        id: autoId,
        codigo: `T-00${autoId}`,
        fecha,
        horaInicio: "12:00",
        horaFin: "13:00",
        alumno,
        profesor: { id: prof.id, nombre: prof.nombre, apellido: prof.apellido },
        materia: { id: mat.id, nombre: mat.nombre, duracionClaseMinutos: mat.duracionMinutos },
        estado: "Cancelado",
        puedeModificar: false,
        puedeCancelar: false,
        cantidadModificaciones: 0,
        cancelacionTardia: true,
        pagado: false,
        observaciones: "Cancelado con aviso previo.",
      });
    }
  });

  return turnos;
}

export const MOCK_TURNOS_INICIALES: TurnoCalendario[] = generarTurnosCompletos();
