// src/modules/alumnos/mock-students.ts
//
// Datos iniciales de prueba para el módulo de Gestión de Alumnos (HU-ALU-02).
// Respeta estrictamente los contratos de API y reproduce fielmente los casos
// de prueba visibles en las capturas de diseño (alumnos con turnos futuros,
// con deudas, inactivos y menores de edad).

import type { StudentUI, StudentAuditLog } from "./types";

export const INITIAL_STUDENTS_MOCK: StudentUI[] = [
  {
    id: 1,
    legajo: "A-0151",
    nombre: "Emma",
    apellido: "Benitez",
    dni: "47880123",
    fechaNacimiento: "2008-03-12",
    telefono: "3874112233",
    email: "emma.benitez@mail.com",
    nivelEducativo: "Secundario",
    responsable: {
      nombre: "Marcos Benitez",
      dni: "24556677",
      telefono: "3874998877",
    },
    estado: "activo",
    institucionOrigen: "Colegio Belgrano",
    observacionesGenerales: "Requiere apoyo para ingreso a la universidad.",
    materiasInteres: [{ id: 1, nombre: "Matemática" }],
    deudaPendiente: false,
    hasPendingDebt: false,
    futureTurnsCount: 0,
    turnosFuturos: [],
    fechaCreacion: "2026-02-10T10:00:00.000Z",
    fechaActualizacion: "2026-03-01T14:30:00.000Z",
  },
  {
    id: 2,
    legajo: "A-0138",
    nombre: "Lara",
    apellido: "Castillo",
    dni: "46120987",
    fechaNacimiento: "2007-09-20",
    telefono: "3874223344",
    email: "lara.castillo@mail.com",
    nivelEducativo: "Secundario",
    responsable: {
      nombre: "Patricia Gomez",
      dni: "23889900",
      telefono: "3874119922",
    },
    estado: "activo",
    institucionOrigen: "Instituto San Martín",
    observacionesGenerales: "Clases los días martes y jueves.",
    materiasInteres: [
      { id: 1, nombre: "Matemática" },
      { id: 2, nombre: "Física" },
    ],
    deudaPendiente: false,
    hasPendingDebt: false,
    futureTurnsCount: 0,
    turnosFuturos: [],
    fechaCreacion: "2026-01-15T09:00:00.000Z",
    fechaActualizacion: "2026-02-18T16:20:00.000Z",
  },
  {
    id: 3,
    legajo: "A-0097",
    nombre: "Tomás",
    apellido: "Gil",
    dni: "45009876",
    fechaNacimiento: "2003-11-05",
    telefono: "3874334455",
    email: "tomas.gil@mail.com",
    nivelEducativo: "Universitario",
    responsable: null,
    estado: "inactivo",
    institucionOrigen: "UNSa - Facultad de Ciencias Exactas",
    observacionesGenerales: "Suspendió temporalmente sus clases por trabajo.",
    materiasInteres: [{ id: 4, nombre: "Inglés" }],
    deudaPendiente: false,
    hasPendingDebt: false,
    futureTurnsCount: 0,
    turnosFuturos: [],
    fechaCreacion: "2025-09-01T11:00:00.000Z",
    fechaActualizacion: "2026-01-20T10:15:00.000Z",
  },
  {
    id: 4,
    legajo: "A-0144",
    nombre: "Mateo",
    apellido: "Herrera",
    dni: "47002315",
    fechaNacimiento: "2008-01-18",
    telefono: "3874445566",
    email: "mateo.herrera@mail.com",
    nivelEducativo: "Secundario",
    responsable: {
      nombre: "Claudio Herrera",
      dni: "25667788",
      telefono: "3874332211",
    },
    estado: "activo",
    institucionOrigen: "Escuela Técnica N° 2",
    observacionesGenerales: "Preparación para exámenes trimestrales.",
    materiasInteres: [
      { id: 4, nombre: "Inglés" },
      { id: 5, nombre: "Lengua" },
    ],
    deudaPendiente: false,
    hasPendingDebt: false,
    futureTurnsCount: 0,
    turnosFuturos: [],
    fechaCreacion: "2026-02-01T08:30:00.000Z",
    fechaActualizacion: "2026-02-25T11:45:00.000Z",
  },
  {
    id: 5,
    legajo: "A-0120",
    nombre: "Irene",
    apellido: "López",
    dni: "44567123",
    fechaNacimiento: "2002-07-22",
    telefono: "3874556677",
    email: "irene.lopez@mail.com",
    nivelEducativo: "Universitario",
    responsable: null,
    estado: "activo",
    institucionOrigen: "Universidad Católica de Salta",
    observacionesGenerales: "Horarios rotativos.",
    materiasInteres: [{ id: 3, nombre: "Química" }],
    // CASO B PARA TESTEAR LA BAJA: Tiene deuda pendiente pero 0 turnos futuros
    deudaPendiente: true,
    hasPendingDebt: true,
    futureTurnsCount: 0,
    turnosFuturos: [],
    detalleDeuda: {
      clasesSinPagar: 2,
      montoTotal: 36000,
      descripcion: "2 clases sin pagar · $ 36.000,00. Podés continuar con la baja; la deuda queda registrada.",
    },
    fechaCreacion: "2025-11-10T12:00:00.000Z",
    fechaActualizacion: "2026-03-05T15:10:00.000Z",
  },
  {
    id: 6,
    legajo: "A-0142",
    nombre: "Juan",
    apellido: "Ortiz",
    dni: "45123987",
    // Menor de 18 (16 años) según captura de pantalla
    fechaNacimiento: "2010-05-14",
    telefono: "3874556677",
    email: "juan.ortiz@mail.com",
    nivelEducativo: "Secundario",
    responsable: {
      nombre: "Silvia Ortiz",
      dni: "23456781",
      telefono: "3874112233",
    },
    estado: "activo",
    institucionOrigen: "Colegio Nacional N.º 5041",
    observacionesGenerales: "Prepara el ingreso a Ingeniería. Prefiere turnos después de las 14 h.",
    materiasInteres: [
      { id: 1, nombre: "Matemática" },
      { id: 2, nombre: "Física" },
    ],
    // CASO A PARA TESTEAR LA BAJA: Tiene 3 turnos futuros reservados (Bloqueo)
    deudaPendiente: false,
    hasPendingDebt: false,
    futureTurnsCount: 3,
    turnosFuturos: [
      {
        id: "T-004512",
        fechaHora: "Lun 28/09 · 15:00",
        materia: "Matemática",
        estado: "Reservado",
      },
      {
        id: "T-004560",
        fechaHora: "Lun 05/10 · 15:00",
        materia: "Matemática",
        estado: "Reservado",
      },
      {
        id: "T-004571",
        fechaHora: "Jue 08/10 · 16:00",
        materia: "Física",
        estado: "Reservado",
      },
    ],
    fechaCreacion: "2026-03-12T09:00:00.000Z",
    fechaActualizacion: "2026-03-12T09:00:00.000Z",
  },
  {
    id: 7,
    legajo: "A-0089",
    nombre: "Ana",
    apellido: "Quiroga",
    dni: "43998112",
    fechaNacimiento: "2001-08-14",
    telefono: "3874778899",
    email: "ana.quiroga@mail.com",
    nivelEducativo: "Universitario",
    responsable: null,
    estado: "inactivo",
    institucionOrigen: "Universidad Nacional de Salta",
    observacionesGenerales: "Egresada.",
    materiasInteres: [{ id: 3, nombre: "Química" }],
    deudaPendiente: false,
    hasPendingDebt: false,
    futureTurnsCount: 0,
    turnosFuturos: [],
    fechaCreacion: "2025-08-04T10:12:00.000Z",
    fechaActualizacion: "2026-07-12T11:20:00.000Z",
  },
  {
    id: 8,
    legajo: "A-0130",
    nombre: "Camila",
    apellido: "Rojas",
    dni: "46778120",
    fechaNacimiento: "2007-04-25",
    telefono: "3874889900",
    email: "camila.rojas@mail.com",
    nivelEducativo: "Secundario",
    responsable: {
      nombre: "Estela Rojas",
      dni: "26112233",
      telefono: "3874221100",
    },
    estado: "activo",
    institucionOrigen: "Colegio San José",
    observacionesGenerales: "Acompañamiento en física teórica.",
    materiasInteres: [{ id: 2, nombre: "Física" }],
    deudaPendiente: false,
    hasPendingDebt: false,
    futureTurnsCount: 0,
    turnosFuturos: [],
    fechaCreacion: "2026-01-28T14:00:00.000Z",
    fechaActualizacion: "2026-02-14T09:30:00.000Z",
  },
];

export const INITIAL_AUDIT_LOGS_MOCK: StudentAuditLog[] = [
  {
    id: 1,
    alumnoId: 7, // Ana Quiroga (según captura de detalle 4)
    fecha: "12/07/2026",
    hora: "11:20",
    responsable: "Laura Gómez",
    accion: "Baja",
    campo: "Estado",
    valorAnterior: "Activo",
    valorNuevo: "Inactivo",
    operacion: "UPDATE",
  },
  {
    id: 2,
    alumnoId: 7,
    fecha: "03/05/2026",
    hora: "09:48",
    responsable: "Mariana Castro",
    accion: "Modificación",
    campo: "Materias de interés",
    valorAnterior: "Química, Física",
    valorNuevo: "Química",
    operacion: "UPDATE",
  },
  {
    id: 3,
    alumnoId: 7,
    fecha: "15/02/2026",
    hora: "16:05",
    responsable: "Laura Gómez",
    accion: "Modificación",
    campo: "Institución de origen",
    valorAnterior: "—",
    valorNuevo: "Universidad Nacional de Salta",
    operacion: "UPDATE",
  },
  {
    id: 4,
    alumnoId: 7,
    fecha: "04/08/2025",
    hora: "10:12",
    responsable: "Mariana Castro",
    accion: "Alta",
    campo: "Estado",
    valorAnterior: "—",
    valorNuevo: "Activo",
    operacion: "INSERT",
  },
];
